version: "3"
services: 

 #mariadb-1
 mariadb1:
   image: mariadb:10.11
   container_name: mariadb1
   ports:
    - "3301:3306"
   env_file: .env
   environment:
    - MARIADB_USER=${MARIADB_USER_1}
    - MARIADB_PASSWORD=${MARIADB_PASSWORD_1}
    - MARIADB_DATABASE=${MARIADB_DATABASE_1}
    - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
   volumes:
    - ./mariadb1.cnf:/etc/mysql/mariadb.conf.d/galera.cnf
    - ./reset_pass.sql:/docker-entrypoint-initdb.d/reset_pass.sql
   cap_add:
    - all
   networks:
    - mariadb

 #mariadb-2
 mariadb2:
   image: mariadb:10.11
   container_name: mariadb2
   ports:
    - "3302:3306"
   env_file: .env   
   environment:
    - MARIADB_USER=${MARIADB_USER_2}
    - MARIADB_PASSWORD=${MARIADB_PASSWORD_2}
    - MARIADB_DATABASE=${MARIADB_DATABASE_2}
    - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
   volumes:
    - ./mariadb2.cnf:/etc/mysql/mariadb.conf.d/galera.cnf
    - ./reset_pass.sql:/docker-entrypoint-initdb.d/reset_pass.sql
   cap_add:
    - all
   networks:
    - mariadb

 #mariadb-3
 mariadb3:
   image: mariadb:10.11
   container_name: mariadb3
   ports:
    - "3303:3306"
   env_file: .env
   volumes:
    - ./mariadb3.cnf:/etc/mysql/mariadb.conf.d/galera.cnf
    - ./reset_pass.sql:/docker-entrypoint-initdb.d/reset_pass.sql
   environment:
    - MARIADB_USER=${MARIADB_USER_3}
    - MARIADB_PASSWORD=${MARIADB_PASSWORD_3}
    - MARIADB_DATABASE=${MARIADB_DATABASE_3}
    - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
   cap_add:
    - all
   networks:
    - mariadb
 #haproxy
 haproxy:
   image: haproxy:2.7
   container_name: haproxy
   ports:
    - "3306:3306"
    - "8888:8888"
   volumes:
    - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
   networks:
    - mariadb

networks:
  mariadb:
     driver: bridge
